apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: vilftrmcy-python 
  janus-idp.io/tekton: vilftrmcy-python
  backstage.io/kubernetes-id: vilftrmcy-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vilftrmcy-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml