apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: vilftrmcy-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:dc1b55f79d31a59f92074e8daa53ccf61c69dfc3@sha256:cdfdc7f3c5128991848d447f7b77e97ad34c6269b702c80c08c9e820d8bc1c7d
          name: container-image
